name: Continuous Integration and Deployment

on:
  push:
    branches: 
    - "*"
  pull_request:
    branches: 
    - "*"

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore DeployHeroku
    - name: Build
      run: dotnet build DeployHeroku
  
  deploy: 
    runs-on: ubuntu-latest
    needs: build
    environment: Production

    steps:
      - uses: actions/checkout@v2
      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: "**/appsettings.json"
        env:
          ConnectionStrings.DefaultConnection: ${{ secrets.DB_CONNECTION_STRING}}
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "herokudeploytestci"
          heroku_email: "otaviovb.developer@gmail.com"
          usedocker: true
